import localFont from "next/font/local";
import "./globals.css";
import Loading from "../../loading";
import { Suspense } from "react";
// import { Roboto } from "@next/font/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

// const roboto = Roboto({
//   subsets: ["latin"],
//   weight: ["400", "700"],
// });

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-200">
        <Suspense fallback={<Loading />}>{children}</Suspense>
      </body>
    </html>
  );
}
